# gym environment
use_gpu: false
render_mode: null
# checkpoint
checkpoint_dir: "${paths.data_dir}/checkpoints/"
# simulation
episode_length: 120
ra: 10_000
# action config
heater_limit: 0.75
heater_segments: 12
heater_duration: 1.0
heater_start: 0.0
heater_end: 400
