# gym environment
use_gpu: false
render_mode: null
# checkpoint
checkpoint: "${paths.data_dir}/checkpoints/test/ckpt_ra${ra}.h5"
# simulation
episode_length: 120
rayleigh_number: 10_000
pressure: False
# action config
heater_limit: 0.75
heater_segments: 12
heater_duration: 1.0
control_modes: 6
