defaults:
  - hydra: default
  - env: default
  - paths: default
  - _self_

# wandb configuration
task: generate_dataset

# experiment configuration
split: "train"
type: "ppo" # types: "ppo", "random", "pd", or "zero"
total: 20
parallel: 10

ra: 10_000
base_seed: 42
out_dir: ${paths.data_dir}/datasets/2D-control/${split}/ra${ra}

# environment
env:
  render_mode: human
  rayleigh_number: ${ra}
  episode_length: 300
  checkpoint: ${paths.data_dir}/checkpoints/${split}/ckpt_ra${ra}.h5
  heater_duration: 1.0
  heater_segments: 6

ppo:
  model_dir: ${paths.model_dir}/ra${ra}
  model_name: "v1"

random:
  steps: 10

pd:
  kp: 970
  kd: 2000
  bcT: [2, 1]
  limit: ${env.heater_limit}
  heater_duration: ${env.heater_duration}
  heater_segments: ${env.heater_segments}
  obs_shape: [3, 8, 48]
