# Config file for evaluating the Single-Agent (SA) version of the RBC controller

defaults:
  - hydra: default
  - env: default
  - paths: default
  - _self_

# wandb configuration
task: sbsa_eval
tags:
  - eval

# experiment configuration
ra: 10_000
experiment_dir: ${paths.work_dir}/models/ra10000_equal
model_name: "best_model"
debug_cell_dist: False

# fixed parameters
nr_episodes: 20
fps: 4

env:
  ra: ${ra}
  episode_length: 300
  checkpoint: ${paths.data_dir}/checkpoints/test/ckpt_ra${ra}.h5
  render_mode: "rgb_array"
  heater_duration: 1
  control_modes: 4
