# Config file for evaluating the Single-Agent (SA) version of the RBC controller

defaults:
  - hydra: default
  - env: default
  - paths: default
  - _self_

# wandb configuration
task: sbsa_test

# experiment configuration
ra: 10_000
experiment_dir: ${paths.model_dir}/ra10000_new
model_name: "best_model"

# environment
env:
  ra: ${ra}
  episode_length: 300
  checkpoint: ${paths.data_dir}/checkpoints/test/ckpt_ra${ra}.h5
  heater_duration: 1
  control_modes: 4
