# path to data directory
data_dir: ${hydra:runtime.cwd}/data/

# path to logging directory
log_dir: ${hydra:runtime.cwd}/logs/

# path to output directory
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}

# path to model weights
model_dir: ${hydra:runtime.cwd}/models/